version: '3.8'

services:
  my_api:
    container_name: api_auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - my_db
    command: npx nest start --watch
    restart: unless-stopped

  my_db:
    container_name: api_auth_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped